# Generated by Django 3.0 on 2021-05-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(blank=True, max_length=30)),
                ('option_two', models.CharField(blank=True, max_length=30)),
                ('option_three', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
